# Generated by Django 5.1.1 on 2024-11-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='media/blog_imgs')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('isReported', models.BooleanField(default=True)),
            ],
        ),
    ]
