# Generated by Django 5.1.1 on 2024-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_msg', models.TextField()),
                ('image_link', models.ImageField(upload_to='')),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
