# Generated by Django 5.1.1 on 2024-10-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_link',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
