# Generated by Django 5.1.1 on 2024-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='isApproved',
            field=models.IntegerField(choices=[(-1, 'Pending'), (0, 'Declined'), (1, 'Published')], default='Pending'),
        ),
    ]
