# Generated by Django 5.1.1 on 2024-10-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
