# Generated by Django 5.1.1 on 2024-10-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_pictures')),
                ('program', models.CharField(choices=[('BSCS', 'BSCS'), ('BSIT', 'BSIT')], default='None', max_length=4)),
                ('batch_year', models.IntegerField(choices=[(2028, 2028), (2027, 2027), (2026, 2026), (2025, 2025), (2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987)], default=2024)),
                ('quote', models.TextField(blank=True, max_length=250, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, max_length=250, null=True)),
                ('facebook_link_hidden', models.BooleanField(default=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, max_length=250, null=True)),
                ('linkedin_link_hidden', models.BooleanField(default=True, null=True)),
                ('github_link', models.TextField(blank=True, max_length=250, null=True)),
                ('github_link_hidden', models.BooleanField(default=True, null=True)),
                ('instagram_link', models.TextField(blank=True, max_length=250, null=True)),
                ('instagram_link_hidden', models.BooleanField(default=True, null=True)),
                ('is_hide', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
