# Generated by Django 5.1.1 on 2024-10-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('program', models.CharField(max_length=50, null=True)),
                ('batch_year', models.IntegerField(null=True)),
                ('quote', models.TextField(max_length=250, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('favorite_quote', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(max_length=250, null=True)),
                ('linkedin_link', models.TextField(max_length=250, null=True)),
                ('github_link', models.TextField(max_length=250, null=True)),
                ('instagram_link', models.TextField(max_length=250, null=True)),
            ],
        ),
    ]
