# Generated by Django 5.1.1 on 2024-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_links',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='id_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='id_images/'),
        ),
    ]
