# Generated by Django 5.1.1 on 2024-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_id_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
