# Generated by Django 5.1.1 on 2024-10-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hide',
            field=models.BooleanField(null=True),
        ),
    ]
