# Generated by Django 5.1.1 on 2024-09-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_is_id_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_id_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
