# Generated by Django 5.1.1 on 2024-09-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_id_back_and_more'),
        ('user_management', '0003_remove_useraccount_favorite_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='batch_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_link',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_link',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_link',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_link',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quote',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.useraccount'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
