# Generated by Django 5.1.1 on 2024-09-27 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.FileField(blank=True, null=True, upload_to='id_images/')),
                ('id_back', models.FileField(blank=True, null=True, upload_to='id_images/')),
                ('is_acc_verified', models.BooleanField(default=False)),
                ('favorite_quote', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
