# Generated by Django 5.1.1 on 2024-12-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(help_text='Required. 10 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=10, unique=True),
        ),
    ]
