# Generated by Django 5.1.1 on 2024-09-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id_back',
            field=models.ImageField(blank=True, height_field=60, null=True, upload_to='media/id_images/back', width_field=60),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_front',
            field=models.ImageField(blank=True, height_field=60, null=True, upload_to='media/id_images/front', width_field=60),
        ),
    ]
