# Generated by Django 5.1.1 on 2024-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_useraccount_id_back_alter_useraccount_id_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/id_images/back'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/id_images/front'),
        ),
    ]
