# Generated by Django 5.1.1 on 2024-09-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_useraccount_id_back_alter_useraccount_id_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='favorite_quote',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='default-password', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='photo_w_id',
            field=models.ImageField(blank=True, null=True, upload_to='media/id_images/photo'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='school_id_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='default-username', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/id_images/back'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/id_images/front'),
        ),
    ]
