# Generated by Django 5.1.1 on 2024-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
