# Generated by Django 5.1.1 on 2024-11-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_report_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_item_id',
        ),
    ]
