# Generated by Django 5.1.1 on 2024-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_report_report_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
